name: Build

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    container: wpilib/roborio-cross-ubuntu:2025-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Grant execute permission
        run: chmod +x gradlew
      # - name: Install roboRio toolchain
      #   run: ./gradlew installRoboRioToolchain
      - name: Build robot code
        run: ./gradlew build